# Generated by Django 5.2.7 on 2025-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollection',
            name='background_color',
            field=models.CharField(default='#f0f0f0', max_length=7),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='font_color',
            field=models.CharField(default='#171717', max_length=7),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='header_color',
            field=models.CharField(default='#100e75', max_length=7),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='header_font_color',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='header_text_left',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
