# Generated by Django 5.2.7 on 2025-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardcollection_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='header_right',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
