# Generated by Django 5.2.8 on 2025-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_header_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollection',
            name='font_family',
            field=models.CharField(default='Arial', max_length=200),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='height_mm',
            field=models.DecimalField(decimal_places=2, default=53.98, max_digits=6),
        ),
        migrations.AddField(
            model_name='flashcardcollection',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, default=85.6, max_digits=6),
        ),
    ]
