# Generated by Django 5.2.8 on 2026-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcardcollection_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_info_card',
            field=models.BooleanField(default=False),
        ),
    ]
